/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.monopoly.gui.panels;

import com.monopoly.app.Giocatore;
import java.util.InputMismatchException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo Lepore - Matricola: 172416
 */
@SuppressWarnings("SpellCheckingInspection")
public class PayTaxPanel extends javax.swing.JPanel {

    private final JFrame actualFrame;
    private final GameboardPanel gameboardPanel;
    private final Giocatore giocatoreAttuale;

    /**
     * Creates new form PayTaxPanel
     */
    public PayTaxPanel(JFrame actualFrame, Giocatore giocatoreAttuale, GameboardPanel gameboardPanel) {
        initComponents();
        this.actualFrame = actualFrame;
        this.giocatoreAttuale = giocatoreAttuale;
        this.gameboardPanel = gameboardPanel;
        
        this.annullaButton.addActionListener(
                ActionEvent -> HandleAnnullaButton()
        );
        
        this.confermaPagamentoButton.addActionListener(
                ActionEvent -> HandleConfermaPagamentoButton()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tassaTextField = new javax.swing.JTextField();
        confermaPagamentoButton = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Importo tassa");

        confermaPagamentoButton.setText("Conferma pagamento");

        annullaButton.setText("Annulla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(annullaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confermaPagamentoButton))
                    .addComponent(tassaTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tassaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confermaPagamentoButton)
                    .addComponent(annullaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaButton;
    private javax.swing.JButton confermaPagamentoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tassaTextField;
    // End of variables declaration//GEN-END:variables

    private void HandleAnnullaButton(){
        this.actualFrame.dispose();
    }    
    
    private void HandleConfermaPagamentoButton(){
        try {
            
            int importo = Integer.parseInt(tassaTextField.getText());
            
            if (importo > 0 && importo <= giocatoreAttuale.getDenaro()) {
                giocatoreAttuale.addDenaro(-Integer.parseInt(tassaTextField.getText()));
                JOptionPane.showMessageDialog(
                        this.getParent(),
                        "Importo di " + importo + "$ decurtato dal vostro conto.",
                        "Pagamento effettuato",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                this.gameboardPanel.updateInfoTextArea();
                this.actualFrame.dispose();
                
            } else {
                JOptionPane.showMessageDialog(
                        this.getParent(),
                        "Importo non valido. Riprovare.",
                        "Errore nell'input",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(
                    this.getParent(),
                    "Importo non valido. Riprovare.",
                    "Errore nell'input",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }
}
