/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.monopoly.gui.panels;

import com.monopoly.app.Contratto;
import com.monopoly.app.GestoreContratti;
import com.monopoly.app.Giocatore;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lorenzo Lepore - Matricola: 172416
 */
@SuppressWarnings("SpellCheckingInspection")
public class BuyContractPanel extends javax.swing.JPanel {
    private final JFrame actualFrame;
    private final GestoreContratti gestoreContratti;
    private final Giocatore giocatoreAttuale;
    private final ArrayList<Contratto> contrattiDisponibili;
    private final GameboardPanel gameboardPanel;
    private int denaroBeforeAcquisto;

    /**
     * Creates new form BuyContractPanel
     * @param actualFrame
     * @param gestoreContratti
     * @param giocatoreAttuale
     * @param gameboardPanel
     */
    public BuyContractPanel(JFrame actualFrame,GestoreContratti gestoreContratti, Giocatore giocatoreAttuale, GameboardPanel gameboardPanel) {
        initComponents();
        
        this.actualFrame = actualFrame;
        this.gestoreContratti = gestoreContratti;
        this.giocatoreAttuale = giocatoreAttuale;
        this.gameboardPanel = gameboardPanel;
        
        contrattiDisponibili = new ArrayList<>(this.gestoreContratti.getContratti());
        contrattiDisponibili.removeIf(contratto -> (!contratto.getDisponibile()));
        
        DefaultListModel contrattiListModel = new DefaultListModel();
        
        for (Contratto contratto : contrattiDisponibili) {
            contrattiListModel.addElement(contratto + " (" + contratto.getPrezzoVendita() + "€)");
        }
        
        contrattiList.setModel(contrattiListModel);
        
        this.annullaButton.addActionListener(
                ActionEvent -> HandleAnnullaButton()
        );
        
        this.confermaButton.addActionListener(
                ActionEvent -> HandleConfermaButton()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contrattiList = new javax.swing.JList<>();
        confermaButton = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBackground(new java.awt.Color(204, 255, 204));

        jScrollPane1.setViewportView(contrattiList);

        confermaButton.setText("Conferma");

        annullaButton.setText("Annulla");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selezionare un contratto da acquistare: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(confermaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confermaButton)
                    .addComponent(annullaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annullaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaButton;
    private javax.swing.JButton confermaButton;
    private javax.swing.JList<String> contrattiList;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void HandleAnnullaButton() {
        this.actualFrame.dispose();
    }  
    
    private void HandleConfermaButton() {
        for (Contratto contratto : contrattiDisponibili) {
            if (contrattiList.getSelectedValue().contains(contratto.getNome())){
                
                giocatoreAttuale.addContrattiPosseduti(contratto);
                contratto.setProprietario(giocatoreAttuale);

                denaroBeforeAcquisto = giocatoreAttuale.getDenaro();
                giocatoreAttuale.addDenaro(-contratto.getPrezzoVendita());
                
                contratto.setDisponibile(false);
                
                JOptionPane.showMessageDialog(
                        this.getParent(), 
                        "Contratto acquistato con successo.",
                        "Acquisto effettuato",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                this.gameboardPanel.updateInfoTextArea();
                this.actualFrame.dispose();
            }
        }
    }
}
