/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.monopoly.gui.panels;

import com.monopoly.app.Contratto;
import com.monopoly.app.GestoreContratti;
import com.monopoly.app.GestoreGiocatori;
import com.monopoly.app.GestorePartita;
import com.monopoly.app.GestorePedine;
import com.monopoly.app.Giocatore;
import com.monopoly.gui.frames.PayFrame;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo Lepore - Matricola: 172416
 */
public class PrisonPanel extends javax.swing.JPanel {

    private final JFrame actualFrame;
    private Giocatore giocatoreAttuale;
    private GestoreGiocatori gestoreGiocatori;
    private GestoreContratti gestoreContratti;
    private GestorePedine gestorePedine;
    private GestorePartita gestorePartita;
    
    /**
     * Creates new form GameboardPanel
     * @param givenFrame
     * @param gestoreGiocatori
     * @param gestoreContratti
     * @param gestorePedine
     * @param gestorePartita
     */
    
    public PrisonPanel(
            JFrame givenFrame,  
            GestoreGiocatori gestoreGiocatori, 
            GestoreContratti gestoreContratti, 
            GestorePedine gestorePedine, 
            GestorePartita gestorePartita
            ) {
        
        initComponents();
        
        this.actualFrame = givenFrame;
        this.gestoreGiocatori = gestoreGiocatori;
        this.gestoreContratti = gestoreContratti;
        this.gestorePedine = gestorePedine;
        this.gestorePartita = gestorePartita;
        this.giocatoreAttuale = this.gestoreGiocatori.getGiocatore(this.gestorePartita.getOrdineGiocatori()[this.gestorePartita.getOrdineGiocatoriIndex()]);

        
        updateInfoTextArea();
        prigioneButton.setBackground(Color.green);

        this.esciGratisButton.addActionListener(
                actionEvent -> {
                    handleEsciGratis();
                }
        );
        
        this.esciPagandoButton.addActionListener(
                actionEvent -> handleEsciPagando()
        );
        

        this.restaInPrigioneButton.addActionListener(
                actionEvent -> handleRestaInPrigione()
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parcheggioButton = new javax.swing.JButton();
        piazzaDanteButton = new javax.swing.JButton();
        corsoRaffaelloButton = new javax.swing.JButton();
        viaVerdiButton = new javax.swing.JButton();
        stazioneOvestButton = new javax.swing.JButton();
        piazzaUniversitaButton = new javax.swing.JButton();
        corsoAteneoButton = new javax.swing.JButton();
        viaAccademiaButton = new javax.swing.JButton();
        prigioneButton = new javax.swing.JButton();
        viaMarcoPoloButton = new javax.swing.JButton();
        vialeVesuvioButton = new javax.swing.JButton();
        vialeMonterosaButton = new javax.swing.JButton();
        bastioniGranSassoButton = new javax.swing.JButton();
        corsoMagellanoButton = new javax.swing.JButton();
        largoColomboButton = new javax.swing.JButton();
        stazioneNordButton = new javax.swing.JButton();
        stazioneSudButton = new javax.swing.JButton();
        societaAcquaPotabileButton = new javax.swing.JButton();
        vicoloStrettoButton = new javax.swing.JButton();
        vicoloCortoButton = new javax.swing.JButton();
        viaButton = new javax.swing.JButton();
        vialeCostantinoButton = new javax.swing.JButton();
        vialeTraianoButton = new javax.swing.JButton();
        piazzaGiulioCesareButton = new javax.swing.JButton();
        inPrigioneButton = new javax.swing.JButton();
        viaRomaButton = new javax.swing.JButton();
        corsoImperoButton = new javax.swing.JButton();
        largoAugustoButton = new javax.swing.JButton();
        stazioneEstButton = new javax.swing.JButton();
        societaElettricaButton = new javax.swing.JButton();
        vialeDeiGiardiniButton = new javax.swing.JButton();
        parcoDellaVittoriaButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        esciGratisButton = new javax.swing.JButton();
        esciPagandoButton = new javax.swing.JButton();
        restaInPrigioneButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setEnabled(false);

        parcheggioButton.setText("Parcheggio");

        piazzaDanteButton.setText("Piazza Dante");

        corsoRaffaelloButton.setText("Corso Raffaello");

        viaVerdiButton.setText("Via Verdi");

        stazioneOvestButton.setText("Stazione Ovest");

        piazzaUniversitaButton.setText("Piazza Università");

        corsoAteneoButton.setText("Corso Ateneo");

        viaAccademiaButton.setText("Via Accademia");

        prigioneButton.setText("Prigione");

        viaMarcoPoloButton.setText("Via Marco Polo");

        vialeVesuvioButton.setText("Viale Vesuvio");

        vialeMonterosaButton.setText("Viale Monterosa");

        bastioniGranSassoButton.setText("Bastioni G. Sasso");

        corsoMagellanoButton.setText("Corso Magellano");

        largoColomboButton.setText("Largo Colombo");

        stazioneNordButton.setText("Stazione Nord");

        stazioneSudButton.setText("Stazione Sud");

        societaAcquaPotabileButton.setText("Società acqua pot.");

        vicoloStrettoButton.setText("Vicolo Stretto");

        vicoloCortoButton.setText("Vicolo Corto");

        viaButton.setText("<-- Via");

        vialeCostantinoButton.setText("Viale Costantino");

        vialeTraianoButton.setText("Viale Traiano");

        piazzaGiulioCesareButton.setText("Piazza G. Cesare");

        inPrigioneButton.setText("In Prigione!");

        viaRomaButton.setText("Via Roma");

        corsoImperoButton.setText("Corso Impero");

        largoAugustoButton.setText("Largo Augusto");

        stazioneEstButton.setText("Stazione Est");

        societaElettricaButton.setText("Società elettrica");

        vialeDeiGiardiniButton.setText("Viale dei Giardini");

        parcoDellaVittoriaButton.setText("Parco della Vittoria");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(null);

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        infoTextArea.setAutoscrolls(false);
        jScrollPane1.setViewportView(infoTextArea);

        esciGratisButton.setText("Esci gratis");

        esciPagandoButton.setText("Esci pagando");

        restaInPrigioneButton.setText("Resta in prigione");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(esciGratisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(esciPagandoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restaInPrigioneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(parcheggioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viaMarcoPoloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corsoMagellanoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(largoColomboButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stazioneNordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vialeCostantinoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vialeTraianoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(piazzaGiulioCesareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viaAccademiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viaVerdiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stazioneOvestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(piazzaUniversitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(corsoAteneoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(piazzaDanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(corsoRaffaelloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parcoDellaVittoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(societaElettricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vialeDeiGiardiniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stazioneEstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largoAugustoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corsoImperoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viaRomaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inPrigioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prigioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vialeVesuvioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vialeMonterosaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bastioniGranSassoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stazioneSudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(societaAcquaPotabileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vicoloStrettoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vicoloCortoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parcheggioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viaMarcoPoloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corsoMagellanoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largoColomboButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stazioneNordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vialeCostantinoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vialeTraianoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piazzaGiulioCesareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inPrigioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piazzaDanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viaRomaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corsoRaffaelloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corsoImperoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viaVerdiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largoAugustoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stazioneOvestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stazioneEstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piazzaUniversitaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(societaElettricaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corsoAteneoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vialeDeiGiardiniButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viaAccademiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(parcoDellaVittoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prigioneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vialeVesuvioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vialeMonterosaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bastioniGranSassoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stazioneSudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(societaAcquaPotabileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vicoloStrettoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vicoloCortoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(esciGratisButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(esciPagandoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaInPrigioneButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bastioniGranSassoButton;
    private javax.swing.JButton corsoAteneoButton;
    private javax.swing.JButton corsoImperoButton;
    private javax.swing.JButton corsoMagellanoButton;
    private javax.swing.JButton corsoRaffaelloButton;
    private javax.swing.JButton esciGratisButton;
    private javax.swing.JButton esciPagandoButton;
    private javax.swing.JButton inPrigioneButton;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton largoAugustoButton;
    private javax.swing.JButton largoColomboButton;
    private javax.swing.JButton parcheggioButton;
    private javax.swing.JButton parcoDellaVittoriaButton;
    private javax.swing.JButton piazzaDanteButton;
    private javax.swing.JButton piazzaGiulioCesareButton;
    private javax.swing.JButton piazzaUniversitaButton;
    private javax.swing.JButton prigioneButton;
    private javax.swing.JButton restaInPrigioneButton;
    private javax.swing.JButton societaAcquaPotabileButton;
    private javax.swing.JButton societaElettricaButton;
    private javax.swing.JButton stazioneEstButton;
    private javax.swing.JButton stazioneNordButton;
    private javax.swing.JButton stazioneOvestButton;
    private javax.swing.JButton stazioneSudButton;
    private javax.swing.JButton viaAccademiaButton;
    private javax.swing.JButton viaButton;
    private javax.swing.JButton viaMarcoPoloButton;
    private javax.swing.JButton viaRomaButton;
    private javax.swing.JButton viaVerdiButton;
    private javax.swing.JButton vialeCostantinoButton;
    private javax.swing.JButton vialeDeiGiardiniButton;
    private javax.swing.JButton vialeMonterosaButton;
    private javax.swing.JButton vialeTraianoButton;
    private javax.swing.JButton vialeVesuvioButton;
    private javax.swing.JButton vicoloCortoButton;
    private javax.swing.JButton vicoloStrettoButton;
    // End of variables declaration//GEN-END:variables

    public void updateInfoTextArea(){

        infoTextArea.setText("Turno di " + giocatoreAttuale.getNome() + " (IN PRIGIONE)\nPedina: " + giocatoreAttuale.getPedinaPosseduta().getNome()
                    + "\nDenaro: " + giocatoreAttuale.getDenaro() + " $\n\nContratti posseduti:\n" + giocatoreAttuale.getStringContrattiPosseduti());
        infoTextArea.setCaretPosition(0);

    }    

   private void handleEsciGratis(){
   
       giocatoreAttuale.setInPrigione(false);
       
       JOptionPane.showMessageDialog(
            this.getParent(), 
            "Sei uscito gratis di prigione",
            "Cauzione pagata",
            JOptionPane.INFORMATION_MESSAGE
        );     
       
       handleTerminaTurno();
   }
    
   private void handleEsciPagando(){
   
       giocatoreAttuale.addDenaro(-125);
       giocatoreAttuale.setInPrigione(false);
       
       JOptionPane.showMessageDialog(
            this.getParent(), 
            "Sei uscito di prigione pagando 125$",
            "Cauzione pagata",
            JOptionPane.INFORMATION_MESSAGE
        ); 
   
        handleTerminaTurno();
   }
   
   private void handleRestaInPrigione(){
   
        handleTerminaTurno();
       
   }
   
   private void handleTerminaTurno(){
   
        this.gestorePartita.setOrdineGiocatoriIndex(this.gestorePartita.getOrdineGiocatoriIndex() + 1);

        if(this.gestorePartita.getOrdineGiocatoriIndex()==this.gestoreGiocatori.getNumeroGiocatori()){
            
            this.gestorePartita.setGiri(this.gestorePartita.getGiri() + 1);
            this.gestorePartita.setOrdineGiocatoriIndex(0);
         
        }

        if(this.gestorePartita.getGiri() == 5){

            String giocatoreVincitore = new String();
            int denaroVincitore = 0;

            for(Giocatore giocatore : this.gestoreGiocatori.getGiocatori()){
                for(Contratto contratto: giocatore.getContrattiPosseduti()){
                    giocatore.addDenaro(contratto.getPrezzoVendita());
                }
            }

            for(Giocatore giocatore : this.gestoreGiocatori.getGiocatori()){
                if(giocatore.getDenaro()>denaroVincitore){
                    denaroVincitore = giocatore.getDenaro();
                    giocatoreVincitore = giocatore.getNome();
                }
            }

            JOptionPane.showMessageDialog(
                    this.getParent(),
                    "VINCE " + giocatoreVincitore + "!",
                    "Partita terminata",
                    JOptionPane.INFORMATION_MESSAGE
            );

            System.exit(0);

        }

        if(this.gestoreGiocatori.getGiocatore(this.gestorePartita.getOrdineGiocatori()[this.gestorePartita.getOrdineGiocatoriIndex()]).getInPrigione()==true){
            this.setVisible(false);
            PrisonPanel newPrisonPanel = new PrisonPanel(
                    this.actualFrame,
                    this.gestoreGiocatori,
                    this.gestoreContratti,
                    this.gestorePedine,
                    this.gestorePartita
            );
            this.actualFrame.setContentPane(newPrisonPanel);        
        } else if (this.gestoreGiocatori.getGiocatore(this.gestorePartita.getOrdineGiocatori()[this.gestorePartita.getOrdineGiocatoriIndex()]).getInPrigione()==false){
            this.setVisible(false);
            GameboardPanel newGameboardPanel = new GameboardPanel(
                    this.actualFrame,
                    this.gestoreGiocatori,
                    this.gestoreContratti,
                    this.gestorePedine,
                    this.gestorePartita
            );
            this.actualFrame.setContentPane(newGameboardPanel);
        }
   }
}
