/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.monopoly.gui.frames;

import com.monopoly.app.GestoreContratti;
import com.monopoly.app.Giocatore;
import com.monopoly.gui.panels.BuyContractPanel;
import com.monopoly.gui.panels.GameboardPanel;
import com.monopoly.gui.panels.PayRentPanel;
import com.monopoly.gui.panels.PayTaxPanel;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Lorenzo Lepore - Matricola: 172416
 */
@SuppressWarnings("SpellCheckingInspection")
public class PayFrame extends javax.swing.JFrame {
    private final GestoreContratti gestoreContratti;
    private final Giocatore giocatoreAttuale;
    private final GameboardPanel gameboardPanel;
    
    /**
     * Creates new form PayFrame
     * @param startCode
     */
    public PayFrame(int startCode, GestoreContratti gestoreContratti, Giocatore giocatoreAttuale, GameboardPanel gameboardPanel) {
        initComponents();

        this.gestoreContratti = gestoreContratti;
        this.giocatoreAttuale = giocatoreAttuale;
        this.gameboardPanel = gameboardPanel;

        switch(startCode){
        
            case 1:
                this.setTitle("Acquisto contratto");
                BuyContractPanel buyContractPanel = new BuyContractPanel(this,this.gestoreContratti,this.giocatoreAttuale,this.gameboardPanel);
                this.setContentPane(buyContractPanel);
            break;
                
            case 2: 
                this.setTitle("Pagamento affitto");
                PayRentPanel payRentPanel = new PayRentPanel(this,this.gestoreContratti,this.giocatoreAttuale,this.gameboardPanel);
                this.setContentPane(payRentPanel);   

            break;
            
            case 3: 
                this.setTitle("Pagamento tassa");
                PayTaxPanel payTaxPanel = new PayTaxPanel(this,this.giocatoreAttuale,this.gameboardPanel);
                this.setContentPane(payTaxPanel);    
            break;
           
        }

        this.pack();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new PayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
